name: Cleanup ğŸ§¼

on:
  delete:
  workflow_dispatch:


jobs:

  cleanup-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'

      - name: Remove unused builds ğŸ—‘
        run: |
          sh remove-unused-builds.sh
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "Remove unused builds ğŸ§¼"

      - name: Apply Changes ğŸ§¼
        uses: ad-m/github-push-action@master
        with:
          branch: 'gh-pages'