name: Cleanup ğŸ§¼

on:
  delete:
  workflow_dispatch:


jobs:

  cleanup-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'


      - name: Remove unused Builds ğŸ—‘
        #remove every folder that has no branch name in it
        run: sh remove-unused-builds.sh