name: Cleanup ğŸ§¼

on:
  delete:
  workflow_dispatch:


jobs:

  cleanup-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'

      - name: Remove unused builds ğŸ—‘
        run: sh remove-unused-builds.sh

      - name: Apply Changes cleanup ğŸš€
        run: |
          git commit -m "Cleanup ğŸ§¼"
          git push origin gh-pages