name: Build and Deploy
on:
  workflow_dispatch:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!prod'     # excludes master
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3

      - name: Get env
        run: echo "repo_name=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV



      - name: Prep Files üìù
        run: |
          cat << EOF > ./src/config.json
            {
              "apiKey": "${{secrets.API_KEY}}",
              "authDomain": "${{secrets.AUTH_DOMAIN}}",
              "databaseURL": "${{secrets.DATABASE_URL}}",
              "projectId": "${{secrets.PROJECT_ID}}",
              "storageBucket": "${{secrets.STORAGE_BUCKET}}",
              "messagingSenderId": "${{secrets.MESSAGING_SENDER_ID}}",
              "appId": "${{secrets.APP_ID}}",
              "measurementId": "${{secrets.MEASUREMENT_ID}}"
            }
          EOF
          sed -ri "s/PUBLIC_PATH/${{ env.repo_name }}\/${{github.ref_name}}/g" ./vue.config.js
          sed -ri "s/mode: 'history'/mode: 'hash'/g" ./src/router/index.ts

      - name: Install and Build üîß # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
          branch: gh-pages
          target-folder: ${{github.ref_name}}
